### ISSUE TITLE
[TS23] Testar Usabilidade CCA

### ISSUE THREAD

**Issue by ulyssesBML** [fga-gpp-mds/2018.1_Gerencia_mais#103]
## 🔵 Testar Usabilidade

* ### Descrição
**Eu, como** desenvolvedor
**Desejo** testar a usabilidade (design) do sistema usando o  __Colour Contrast Analyser__
**Para** garantir a boa usabilidade do sistema

**Comment by Guilherme-Aguiar** [comment]
Usabilidade testada, relatório presente no drive.
