### ISSUE TITLE
[TS32] Atualizar diagrama de classe 

### ISSUE THREAD

**Issue by joaosaliba** [fga-gpp-mds/2018.1_Gerencia_mais#152]
* ### Descrição
atualizar diagrama de classe de acordo com projeto

**Comment by joaosaliba** [comment]
remanejada para outro integrante.

**Comment by hiluluk** [comment]
![classdiagram](https://user-images.githubusercontent.com/31783143/40567451-bf62b0ba-604b-11e8-9b13-c32ad97d5442.png)
