### ISSUE TITLE
Erro no travis para o postgres

### ISSUE THREAD

**Issue by victorhdcoelho** [fga-gpp-mds/2018.1_Gerencia_mais#195]
### Descrição
O travis não está dando build no docker-compose, então por isso acho que ele não está subindo o service do postgres. E por conta disso acho que as migrations estão dando errado.

## Erro
[Link de erro](https://travis-ci.org/fga-gpp-mds/2018.1_Gerencia_mais/builds/380480857?utm_source=github_status&utm_medium=notification)

**Comment by Eduardojvr** [comment]
Corrigido! 
https://travis-ci.org/fga-gpp-mds/2018.1_Gerencia_mais

Vai ser necessário adaptar os testes
