### ISSUE TITLE
Estudar viabilidade de implementar algum dos micro serviços abaixo:

### ISSUE THREAD

**Issue by Eduardojvr** [fga-gpp-mds/2018.1_Gerencia_mais#206]
## Geração de pdf com quadro horário de cada médico
- Viável?
- [x] Sim
- [ ] Não

## Bot inteligente de ajuda ao usuário
- Viável?
- [ ] Sim
- [x] Não

**Comment by joaosaliba** [comment]
Dois micro serviços foram implementados: envio de email, e geração de relatório
