### ISSUE TITLE
Permissão restrita em pasta do django

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [fga-gpp-mds/2018.1_Gerencia_mais#23]
Usei o sudo docker-compose up para criar o container, até ai tudo bem, depois abri outro terminal, e na pasta do projeto do django mandei um

>  sudo docker exec -it projeto_django_1 python manage.py startapp meuapp

já que sem sudo dá um erro:
![captura de tela de 2018-03-16 17-09-39](https://user-images.githubusercontent.com/23269406/37542441-f4ef6eb2-293c-11e8-92f5-3151af450ac0.png)
o problema é que essa pasta ''app'' está com permissão restrita:
![captura de tela de 2018-03-16 17-11-34](https://user-images.githubusercontent.com/23269406/37542508-2b78fa5c-293d-11e8-9869-59bf72c3c61b.png)
eu não consigo salvar nada na pasta app, e só consigo criar com sudo.
triste

**Comment by Eduardojvr** [comment]
Tente: sudo chmod 777 .

**Comment by viniciusbandeira** [comment]
Quando você cria um container usando sudo, tudo que é criado pertence ao usuário root do sistema, [configure seu docker-compose  para não precisar de sudo](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user), e não ter problemas com permissão.
O chmod 777 resolve a consequência mas não a causa pois libera todas as restrições ao invés de direcionar ao usuário correto , o que pode criar um ponto de vulnerabilidade de segurança no ambiente do seu software.

**Comment by Guilherme-Aguiar** [comment]
Realmente eu não preciso mais de sudo para dar o "docker exec... startapp meuapp", mas continua criando uma pasta com que não da pra escrever

**Comment by Eduardojvr** [comment]
Estou procurando soluções para o problema, até o final da semana subirei a correção!

**Comment by Eduardojvr** [comment]
De acordo com a documentação isso só seria resolvido com grupos de usuário, mas isso cria problemas sérios de segurança, usem o sudo para isso!
