### ISSUE TITLE
[TS58]Adaptar código com micro serviço de enviar quadros horários

### ISSUE THREAD

**Issue by joaosaliba** [fga-gpp-mds/2018.1_Gerencia_mais#251]
eu como desenvolver 
desejo que seja adaptado código com microserviço
para que o mesmo possa efetuar função de enviar quadro horário por email

* ### Tasks
- [x] adicionar campo email ao cadastro de médicos

**Comment by Eduardojvr** [comment]
Leiam o Readme https://github.com/Eduardojvr/notifica_mais
