### ISSUE TITLE
Elaborar Plano de Gerenciamento de Custo

### ISSUE THREAD

**Issue by CaioGabrielAraujo** [fga-gpp-mds/2018.1_Gerencia_mais#48]
* ### Descrição
Issue criada com o objetivo de controlar a elaboração do plano de gerenciamento de custos do projeto GIC incluindo os processos envolvidos em planejamento, estimativas, orçamentos, financiamentos, gerenciamento e controle dos custos, entre outros.
* ### Controle de documentação     

- [x] Abertura do Documento
- [x] Definir metodologia
- [x] Estimar custos
- [x] Determinar Orçamentos
- [ ] Controle

**Comment by RochaCarla** [comment]
Não existe esse plano
