### ISSUE TITLE
[TS07] - Elaborar Prototipo alta fidelidade

### ISSUE THREAD

**Issue by ulyssesBML** [fga-gpp-mds/2018.1_Gerencia_mais#6]
Eu, como desenvolvedor
Desejo elaborar o protótipo de alta fidelidade
Para validar funcionalidades com os clientes.

**Comment by hiluluk** [comment]
[protoio-prototipo-html.zip](https://github.com/fga-gpp-mds/2018.1_Gestao_de_Internacoes_Cirurgicas_GIC/files/1878508/protoio-prototipo-html.zip)

**Comment by hiluluk** [comment]
https://ninjastorage.blob.core.windows.net/html/KLJ8LRx/index.html#8d88a14b-e6c6-9b60-760e-de7afcdd8010
